date = "2026-08-31"

[pkg.forc]
version = "0.72.1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.1/forc-binaries-linux_amd64.tar.gz"
hash = "1d90387e69ccce595c552654316318975525e89a6d30f86580886aedb1cef517"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.1/forc-binaries-linux_arm64.tar.gz"
hash = "8eabdb0a1487b6ec96fa94acbf861f5034084dbf9a2503c47190dc86f3f615fe"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.1/forc-binaries-darwin_amd64.tar.gz"
hash = "c80ae1cc740f2418c308e2398162c6f051585d7ab81fc2d970a6b16a146b05b3"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.1/forc-binaries-darwin_arm64.tar.gz"
hash = "11f122e1c86927de13e6dd719946571e65bcfa0a1467507efbd6676f7c33fa0d"

[pkg.forc-client]
version = "0.71.6"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.6/forc-client-0.71.6-linux_amd64.tar.gz"
hash = "af6a229f91b7d88375fa100644f921fec400f2959470ef03b29447adbabd2162"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.6/forc-client-0.71.6-linux_arm64.tar.gz"
hash = "ff0ec2626a1a2ecd5a3eecca5f896e925d88beba33e975d0a86aba84408fcbec"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.6/forc-client-0.71.6-darwin_amd64.tar.gz"
hash = "053939bdfd8ee706765d708c6ae68b77f11062cdf071e4ca458593e740a96a9b"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.6/forc-client-0.71.6-darwin_arm64.tar.gz"
hash = "10069332bca20caba85fbc947f0dda52330711234b0f9666d43bd58fd5c196e7"

[pkg.forc-crypto]
version = "0.71.1"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-linux_amd64.tar.gz"
hash = "8b455b1fd47b482d4fd8f5d4db5043bdb8f7764f69af09903f21fb840b3d862b"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-linux_arm64.tar.gz"
hash = "f4c65cfb6868affa6aad0f6b837e6a688428d2d680b58fac6dd13447a50ce0d7"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-darwin_amd64.tar.gz"
hash = "091303e46e5f40faf94c61a30d042071e5ffe7e26faa964944159a3fed53abc2"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-darwin_arm64.tar.gz"
hash = "7da4702714a32a168c6ae1696af6c14172010463776bd31b6a27f6196d392011"

[pkg.forc-node]
version = "0.71.3"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-linux_amd64.tar.gz"
hash = "ac7009c2475764e08f649c14a3919d9234e25d2e1eea28b8eb62264cf9d60548"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-linux_arm64.tar.gz"
hash = "4f1daf341cf7adfafd592a37e4a6794821d10d89700fdd55732f6a6443e6a6ca"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-darwin_amd64.tar.gz"
hash = "f735e2fab51e29ecfe197546eb5243c1cbee268e4b656beca2614b8b087c66ec"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-darwin_arm64.tar.gz"
hash = "d2c2ed30ccedeaf08e13fc2eab8ed22f9ec51561c1b12ed54d75c9f02e919e62"

[pkg.forc-wallet]
version = "0.16.4"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-linux_amd64.tar.gz"
hash = "601241161a5326600ea3f250a3dff34fe4f80bb9cc5d2866803f5e12599a83ae"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-linux_arm64.tar.gz"
hash = "db9496dd3a20574006644e431017f353cc2b11fa60e9b617ab49e073a062363b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-darwin_amd64.tar.gz"
hash = "a9b181a5b5f68219027c73e9753fb2432d59c73b434d0ba7065b9808028fd281"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-darwin_arm64.tar.gz"
hash = "8fd078c2fdcd6dc14e1573053b5f9fdd703ee0b63d2251532f2917b23a00ce87"

[pkg.fuel-core]
version = "0.48.2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "99bca51f1536593e0435b4b853a706dc1c4dd3cb9a5c675e621ca6056993e1c8"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "d96657abe722030d52aac148b601f21987ff4eb86246a827df238b6e4a975077"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-apple-darwin.tar.gz"
hash = "0a3630157466adc1803bbfcb48bf0ceb154b21b233df746b1d20d3c5a9294392"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-apple-darwin.tar.gz"
hash = "c6674a5c5c4f848b98b39adf164da6d8c2b7e125d4008ad754c96783ecb54aa0"

[pkg.fuel-core-keygen]
version = "0.48.2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "99bca51f1536593e0435b4b853a706dc1c4dd3cb9a5c675e621ca6056993e1c8"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "d96657abe722030d52aac148b601f21987ff4eb86246a827df238b6e4a975077"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-apple-darwin.tar.gz"
hash = "0a3630157466adc1803bbfcb48bf0ceb154b21b233df746b1d20d3c5a9294392"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-apple-darwin.tar.gz"
hash = "c6674a5c5c4f848b98b39adf164da6d8c2b7e125d4008ad754c96783ecb54aa0"
