date = "2026-07-29"

[pkg.forc]
version = "0.72.0"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.0/forc-binaries-linux_amd64.tar.gz"
hash = "89b38b0287c2b4518693a7a4efaf2655971436ef74936c4803ecb5024b1e2f54"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.0/forc-binaries-linux_arm64.tar.gz"
hash = "b3cd5896bf0fd0f96f5df367b673c260a47360dd08a909399c3460d13ae67524"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.0/forc-binaries-darwin_amd64.tar.gz"
hash = "dc6c2d370272d880935fd3580df8972ceceacb37a8b1c53bc41feb3d8073d2ba"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway/releases/download/v0.72.0/forc-binaries-darwin_arm64.tar.gz"
hash = "65b9c03959d3bf3ded80fa88b7c08945f3507c2426a443f6266287462d091aec"

[pkg.forc-client]
version = "0.71.5"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.5/forc-client-0.71.5-linux_amd64.tar.gz"
hash = "6f4c98491e43b31e70d14e193351ed62ed2772aa331f46c70581296a29a9faa4"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.5/forc-client-0.71.5-linux_arm64.tar.gz"
hash = "a8cd13d48e27f52b4ddccf0afb229b518aa1278ca8afbffb0cdf9d14222a1748"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.5/forc-client-0.71.5-darwin_amd64.tar.gz"
hash = "c97192fb81331f824b45fe0ec13e36f1b4c5c69d272cf5ce6d2e6d1473c7d74d"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-client-0.71.5/forc-client-0.71.5-darwin_arm64.tar.gz"
hash = "f37193c23a7320df6ddd5e9ba45d5bf33dbf5666ab675fc14a25e2576f94fea9"

[pkg.forc-crypto]
version = "0.71.1"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-linux_amd64.tar.gz"
hash = "8b455b1fd47b482d4fd8f5d4db5043bdb8f7764f69af09903f21fb840b3d862b"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-linux_arm64.tar.gz"
hash = "f4c65cfb6868affa6aad0f6b837e6a688428d2d680b58fac6dd13447a50ce0d7"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-darwin_amd64.tar.gz"
hash = "091303e46e5f40faf94c61a30d042071e5ffe7e26faa964944159a3fed53abc2"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-crypto-0.71.1/forc-crypto-0.71.1-darwin_arm64.tar.gz"
hash = "7da4702714a32a168c6ae1696af6c14172010463776bd31b6a27f6196d392011"

[pkg.forc-node]
version = "0.71.3"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-linux_amd64.tar.gz"
hash = "ac7009c2475764e08f649c14a3919d9234e25d2e1eea28b8eb62264cf9d60548"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-linux_arm64.tar.gz"
hash = "4f1daf341cf7adfafd592a37e4a6794821d10d89700fdd55732f6a6443e6a6ca"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-darwin_amd64.tar.gz"
hash = "f735e2fab51e29ecfe197546eb5243c1cbee268e4b656beca2614b8b087c66ec"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-node-0.71.3/forc-node-0.71.3-darwin_arm64.tar.gz"
hash = "d2c2ed30ccedeaf08e13fc2eab8ed22f9ec51561c1b12ed54d75c9f02e919e62"

[pkg.forc-wallet]
version = "0.16.4"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-linux_amd64.tar.gz"
hash = "601241161a5326600ea3f250a3dff34fe4f80bb9cc5d2866803f5e12599a83ae"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-linux_arm64.tar.gz"
hash = "db9496dd3a20574006644e431017f353cc2b11fa60e9b617ab49e073a062363b"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-darwin_amd64.tar.gz"
hash = "a9b181a5b5f68219027c73e9753fb2432d59c73b434d0ba7065b9808028fd281"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/forc/releases/download/forc-wallet-0.16.4/forc-wallet-0.16.4-darwin_arm64.tar.gz"
hash = "8fd078c2fdcd6dc14e1573053b5f9fdd703ee0b63d2251532f2917b23a00ce87"

[pkg.fuel-core]
version = "0.48.2"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "99bca51f1536593e0435b4b853a706dc1c4dd3cb9a5c675e621ca6056993e1c8"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "d96657abe722030d52aac148b601f21987ff4eb86246a827df238b6e4a975077"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-apple-darwin.tar.gz"
hash = "0a3630157466adc1803bbfcb48bf0ceb154b21b233df746b1d20d3c5a9294392"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-apple-darwin.tar.gz"
hash = "c6674a5c5c4f848b98b39adf164da6d8c2b7e125d4008ad754c96783ecb54aa0"

[pkg.fuel-core-keygen]
version = "0.48.2"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "99bca51f1536593e0435b4b853a706dc1c4dd3cb9a5c675e621ca6056993e1c8"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "d96657abe722030d52aac148b601f21987ff4eb86246a827df238b6e4a975077"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-aarch64-apple-darwin.tar.gz"
hash = "0a3630157466adc1803bbfcb48bf0ceb154b21b233df746b1d20d3c5a9294392"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/fuel-core/releases/download/v0.48.2/fuel-core-0.48.2-x86_64-apple-darwin.tar.gz"
hash = "c6674a5c5c4f848b98b39adf164da6d8c2b7e125d4008ad754c96783ecb54aa0"
