published_by = "https://github.com/FuelLabs/fuelup/actions/runs/26319861128"
date = "2026-05-23"

[pkg.forc]
version = "0.71.0+nightly.20260523.ce310eb1b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-binaries-0.71.0%2Bnightly.20260523.ce310eb1b5-darwin_amd64.tar.gz"
hash = "ee5c8c8972643fdb469c5137e2a7644a09e02e2428c22993a74cff63e7960f59"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-binaries-0.71.0%2Bnightly.20260523.ce310eb1b5-darwin_arm64.tar.gz"
hash = "44d30d4f50b1ec1c87fa0ba0ce01de940de6e7460d9e4ef23f3320c5261792d1"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-binaries-0.71.0%2Bnightly.20260523.ce310eb1b5-linux_amd64.tar.gz"
hash = "d2d38f59700cdf86734853982a269bf1f1252f87ba49f0e5f8fd1186d15f9bc2"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-binaries-0.71.0%2Bnightly.20260523.ce310eb1b5-linux_arm64.tar.gz"
hash = "7e537b8f6134cee85f251e604c49c783703f49d5b905ec693dc619cbcd3248a7"

[pkg.forc-client]
version = "0.71.2+nightly.20260523.16d1a1f1fd"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-client-0.71.2%2Bnightly.20260523.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "7277504c2fd881459b72cbc24bca36db66ce7bf85df618eb8d82950a882a7bf4"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-client-0.71.2%2Bnightly.20260523.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "30b55c13bb976f395e93dacd0fd7d2d93f5c5f200018ac8ba76bf8092fc52cc3"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-client-0.71.2%2Bnightly.20260523.16d1a1f1fd-linux_amd64.tar.gz"
hash = "25ec8191dffe435c6d1cfc7f104028fbc84e104a4e833d16aa1a8049c0dfb2c9"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-client-0.71.2%2Bnightly.20260523.16d1a1f1fd-linux_arm64.tar.gz"
hash = "04b6aaffe192869cf903bd0d9686cdab55b846d1466f0c07d82a514f46496fca"

[pkg.forc-crypto]
version = "0.71.1+nightly.20260523.16d1a1f1fd"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-crypto-0.71.1%2Bnightly.20260523.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "7ea9976b5c5498f579a9bcfa090b54a606f2de05a1921799df3eb45a99ee341c"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-crypto-0.71.1%2Bnightly.20260523.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "152ff2001ac6eea3511a9561aee929ca2eacd76215bd8a89f421c342fcbc9d39"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-crypto-0.71.1%2Bnightly.20260523.16d1a1f1fd-linux_amd64.tar.gz"
hash = "65d13b84cefa24ba8c4c0e0e0ddd1e5a4fb5cae791a4095fdaf5bbfeb8d674e3"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-crypto-0.71.1%2Bnightly.20260523.16d1a1f1fd-linux_arm64.tar.gz"
hash = "47bf47c6ad6334313dde5951fef91bbe0b1253d83918682e4d1bdbe2991d0708"

[pkg.forc-node]
version = "0.71.3+nightly.20260523.16d1a1f1fd"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-node-0.71.3%2Bnightly.20260523.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "c8b460356fa1b3efe7d6343938eefa2122dad07fde64c7963dec5268b7be806b"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-node-0.71.3%2Bnightly.20260523.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "bba43f2d417da0b9451666da7fd04ae56550cb4474ce4b537cccca4298d0f8dc"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-node-0.71.3%2Bnightly.20260523.16d1a1f1fd-linux_amd64.tar.gz"
hash = "1eb82183b3ed554a3abef2a3f10500c6eda18bef5c36f4c8e66d2374e46f0c6e"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-node-0.71.3%2Bnightly.20260523.16d1a1f1fd-linux_arm64.tar.gz"
hash = "fbba25dd5fd3c3ed015783188b94c78f0229f27c5afef847d1df80743d3928ed"

[pkg.forc-wallet]
version = "0.16.4+nightly.20260523.16d1a1f1fd"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-wallet-0.16.4%2Bnightly.20260523.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "33fb79d60049ef3280f8ffeeae560db679b5f8a2368f23b96debeb16c3ca83a4"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-wallet-0.16.4%2Bnightly.20260523.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "f8350a821b4f9e2e25373f941d76f20e6fc56a94b8ff4362cc31501aadc41e80"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-wallet-0.16.4%2Bnightly.20260523.16d1a1f1fd-linux_amd64.tar.gz"
hash = "c2417096230ae37ff795a93aae7dc08bf3e5a949def34c399f282a1a618ed0db"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/forc-wallet-0.16.4%2Bnightly.20260523.16d1a1f1fd-linux_arm64.tar.gz"
hash = "e33cef014966dc4e013aa10f6312602efdb53ffafaf1415abcfe728d81007995"

[pkg.fuel-core]
version = "0.48.2+nightly.20260523.d7b0ac856a"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-aarch64-apple-darwin.tar.gz"
hash = "e8bd4be7eee5fc182c3174f438fe82b5db562490e00a1c4411071ea947ad744b"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-aarch64-unknown-linux-gnu.tar.gz"
hash = "e415fd33a585bca58fdae9a0c79c2edbc41be05c91389ccee260c85e35e6f49d"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-x86_64-apple-darwin.tar.gz"
hash = "d863b3ff91697a626637825232adb3d6c7ce0e80b2009c22a50808637e54a7ad"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-x86_64-unknown-linux-gnu.tar.gz"
hash = "c0f3a4e5dc85dc661ebd6940ba1a99143c08747dbab90fb3b6874194fda27fd2"

[pkg.fuel-core-keygen]
version = "0.48.2+nightly.20260523.d7b0ac856a"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-aarch64-apple-darwin.tar.gz"
hash = "e8bd4be7eee5fc182c3174f438fe82b5db562490e00a1c4411071ea947ad744b"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-aarch64-unknown-linux-gnu.tar.gz"
hash = "e415fd33a585bca58fdae9a0c79c2edbc41be05c91389ccee260c85e35e6f49d"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-x86_64-apple-darwin.tar.gz"
hash = "d863b3ff91697a626637825232adb3d6c7ce0e80b2009c22a50808637e54a7ad"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260523/fuel-core-0.48.2%2Bnightly.20260523.d7b0ac856a-x86_64-unknown-linux-gnu.tar.gz"
hash = "c0f3a4e5dc85dc661ebd6940ba1a99143c08747dbab90fb3b6874194fda27fd2"
