published_by = "https://github.com/FuelLabs/fuelup/actions/runs/26348693118"
date = "2026-05-24"

[pkg.forc]
version = "0.71.0+nightly.20260524.ce310eb1b5"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-binaries-0.71.0%2Bnightly.20260524.ce310eb1b5-darwin_amd64.tar.gz"
hash = "1015fa9a6ecd2830812e55083e105647f91a8d8f2b70c6abe276211964c3751d"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-binaries-0.71.0%2Bnightly.20260524.ce310eb1b5-darwin_arm64.tar.gz"
hash = "dde7d152e3eeeea12b367ce34d6fb4761e2a5f87731924a6fd46ef40b48f8d6a"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-binaries-0.71.0%2Bnightly.20260524.ce310eb1b5-linux_amd64.tar.gz"
hash = "77f98235fb0424d5cd7e09d7f3a531e3bee370316fca0362d1b1bd75f9649bd2"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-binaries-0.71.0%2Bnightly.20260524.ce310eb1b5-linux_arm64.tar.gz"
hash = "dbd3bacb97daadfb1f5aa4ecf2e4dbef728b0a0822574de0e24073a133d3ca6c"

[pkg.forc-client]
version = "0.71.2+nightly.20260524.16d1a1f1fd"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-client-0.71.2%2Bnightly.20260524.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "79cdf64a11a96aaae318a3317db2f15d82cd08ff5605999484ecbceb13e2ca60"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-client-0.71.2%2Bnightly.20260524.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "ddf90ccae9d456a52b01f7956a5e0e07fc8ff8ac605acc520bb6ed8ca6c15548"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-client-0.71.2%2Bnightly.20260524.16d1a1f1fd-linux_amd64.tar.gz"
hash = "8a1546be29165f908fbf0d10edeab3664f0d71f006c04a7c3e72fdd37f001ca4"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-client-0.71.2%2Bnightly.20260524.16d1a1f1fd-linux_arm64.tar.gz"
hash = "51ed88cccb1e4c779e2e5a310603537cf37650ec4d1bb9129e54b93322fe84fc"

[pkg.forc-crypto]
version = "0.71.1+nightly.20260524.16d1a1f1fd"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-crypto-0.71.1%2Bnightly.20260524.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "706246361bec16851874174240f626fb3df53a343e333b26211d6597c8265c37"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-crypto-0.71.1%2Bnightly.20260524.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "39ddb1be29e685c1620500fef8ceb7552468332b6010d8d8c836a16394a33eda"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-crypto-0.71.1%2Bnightly.20260524.16d1a1f1fd-linux_amd64.tar.gz"
hash = "4e1aa44f1a85d863c6d39ed00383f5c1b7b6d19ab49eb0cb0547e3ba80b5271f"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-crypto-0.71.1%2Bnightly.20260524.16d1a1f1fd-linux_arm64.tar.gz"
hash = "1a9ff7355a3d82979f7a38308ea07f790ef32857eee5a6941686f4e68a1cbb7b"

[pkg.forc-node]
version = "0.71.3+nightly.20260524.16d1a1f1fd"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-node-0.71.3%2Bnightly.20260524.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "737963c98055dc682cc1e97b68cbd7e41953c2e582748d1a5f63a42ada84db0a"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-node-0.71.3%2Bnightly.20260524.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "f44b611ceb7c4ad5908f74cc259472e920cb20d379409bf622cb54ad28c4661c"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-node-0.71.3%2Bnightly.20260524.16d1a1f1fd-linux_amd64.tar.gz"
hash = "7a9895256d7fc943e7f9a0f7ad847a05179d3a7da5c5760f8ca5c78eaa673536"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-node-0.71.3%2Bnightly.20260524.16d1a1f1fd-linux_arm64.tar.gz"
hash = "0c09205b3a24ac1678450f79ba7bee7907c7cccfd5b92ffb57ca16019d2aed2b"

[pkg.forc-wallet]
version = "0.16.4+nightly.20260524.16d1a1f1fd"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-wallet-0.16.4%2Bnightly.20260524.16d1a1f1fd-darwin_amd64.tar.gz"
hash = "5ad00cbcecbbdba7d6ee10227c88781a2a44da129824ccef9cab8cd9e25334f2"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-wallet-0.16.4%2Bnightly.20260524.16d1a1f1fd-darwin_arm64.tar.gz"
hash = "9146d799ed0678a0763d198c7a10eefae59b646ce6c7bbb5ae2e3e14cb970dd0"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-wallet-0.16.4%2Bnightly.20260524.16d1a1f1fd-linux_amd64.tar.gz"
hash = "6d13c547e77429a45f62066aa1a28de811a4719b7d2b4bd2e6d639166a28f23b"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/forc-wallet-0.16.4%2Bnightly.20260524.16d1a1f1fd-linux_arm64.tar.gz"
hash = "2acd2e3277e5dbead6fed7f13aae7ef9bb4a15f401773954d7418283b5ac6597"

[pkg.fuel-core]
version = "0.48.2+nightly.20260524.d7b0ac856a"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-aarch64-apple-darwin.tar.gz"
hash = "603dcaea6c638e75e2e224bbd02e00f97c1dde649b72cdc3f5e03e0edd79cd61"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-aarch64-unknown-linux-gnu.tar.gz"
hash = "c328571550db0ec19094ca354e85a6ff793e3f90e7ee622ea1760c1e8af5899e"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-x86_64-apple-darwin.tar.gz"
hash = "879a275c4517b0cec63eabe7947d603ac831c025a3bee0a0010cbfa770dfa733"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-x86_64-unknown-linux-gnu.tar.gz"
hash = "cb3df102c2c88a4a6ab9934da560bde54cc61f21f8db3658bd871a70df2f19c6"

[pkg.fuel-core-keygen]
version = "0.48.2+nightly.20260524.d7b0ac856a"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-aarch64-apple-darwin.tar.gz"
hash = "603dcaea6c638e75e2e224bbd02e00f97c1dde649b72cdc3f5e03e0edd79cd61"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-aarch64-unknown-linux-gnu.tar.gz"
hash = "c328571550db0ec19094ca354e85a6ff793e3f90e7ee622ea1760c1e8af5899e"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-x86_64-apple-darwin.tar.gz"
hash = "879a275c4517b0cec63eabe7947d603ac831c025a3bee0a0010cbfa770dfa733"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260524/fuel-core-0.48.2%2Bnightly.20260524.d7b0ac856a-x86_64-unknown-linux-gnu.tar.gz"
hash = "cb3df102c2c88a4a6ab9934da560bde54cc61f21f8db3658bd871a70df2f19c6"
