published_by = "https://github.com/FuelLabs/fuelup/actions/runs/30777003688"
date = "2026-08-03"

[pkg.forc]
version = "0.72.0+nightly.20260803.91be236f71"

[pkg.forc.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-binaries-0.72.0%2Bnightly.20260803.91be236f71-darwin_amd64.tar.gz"
hash = "6c2fff326d1a2b0f4fe2c84274a8422fe6bc375dfa25d30cbbd96095bb7a6be8"

[pkg.forc.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-binaries-0.72.0%2Bnightly.20260803.91be236f71-darwin_arm64.tar.gz"
hash = "500860b4567723badc1b5c9837134cb46381b5560024283c54b37e59a5ad8d4b"

[pkg.forc.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-binaries-0.72.0%2Bnightly.20260803.91be236f71-linux_amd64.tar.gz"
hash = "daf3a976efe7ebaa01b9716f1e0c09b4347f10d7de2b3db58360bb4c8c18322a"

[pkg.forc.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-binaries-0.72.0%2Bnightly.20260803.91be236f71-linux_arm64.tar.gz"
hash = "85e1aeed78c2a165ba56e532451f3ea281617f0b870edd53f72eeecb46d1a724"

[pkg.forc-client]
version = "0.71.5+nightly.20260803.9defd02fda"

[pkg.forc-client.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-client-0.71.5%2Bnightly.20260803.9defd02fda-darwin_amd64.tar.gz"
hash = "de113a835ec2d44382764fd97247344bc9d3ab07d45662ea6f0eb0364232079f"

[pkg.forc-client.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-client-0.71.5%2Bnightly.20260803.9defd02fda-darwin_arm64.tar.gz"
hash = "76084675b857e5eeba9c51ad8cd1bc7b06d7838568938999610a5483b587f204"

[pkg.forc-client.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-client-0.71.5%2Bnightly.20260803.9defd02fda-linux_amd64.tar.gz"
hash = "f1da4bee560c622cecdf79a863acef3a76db091a44d7732bf449821dad901400"

[pkg.forc-client.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-client-0.71.5%2Bnightly.20260803.9defd02fda-linux_arm64.tar.gz"
hash = "d77a08a54979f178968f12a4a72f593bef2ee1f8678cc5532ea249a3e1b1ff62"

[pkg.forc-crypto]
version = "0.71.1+nightly.20260803.9defd02fda"

[pkg.forc-crypto.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-crypto-0.71.1%2Bnightly.20260803.9defd02fda-darwin_amd64.tar.gz"
hash = "48b73351f4253f50e72b26e43f6e3663a431e38ffceff0d96a6b2ce916224e60"

[pkg.forc-crypto.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-crypto-0.71.1%2Bnightly.20260803.9defd02fda-darwin_arm64.tar.gz"
hash = "1421c2b122abaea22dd0c98b5304da6ac7f55e483833438480f01022d2658c1f"

[pkg.forc-crypto.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-crypto-0.71.1%2Bnightly.20260803.9defd02fda-linux_amd64.tar.gz"
hash = "9a89577db85cef59df42b3ed9eeeb4b5ed352697cdaca3e15582a1ed316f80b5"

[pkg.forc-crypto.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-crypto-0.71.1%2Bnightly.20260803.9defd02fda-linux_arm64.tar.gz"
hash = "7356798678268092765053524ad320ddeae09fa3e6b58fe393cc63624cac69ff"

[pkg.forc-node]
version = "0.71.3+nightly.20260803.9defd02fda"

[pkg.forc-node.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-node-0.71.3%2Bnightly.20260803.9defd02fda-darwin_amd64.tar.gz"
hash = "23ae3e0a9bcc352303e13fe902635224acc309b7fcef3442d8b473a19c1d4727"

[pkg.forc-node.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-node-0.71.3%2Bnightly.20260803.9defd02fda-darwin_arm64.tar.gz"
hash = "e3ea80e8d3870bfaf5e1aa5e3802712c5117f4dc27045496e95bbd83fc909feb"

[pkg.forc-node.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-node-0.71.3%2Bnightly.20260803.9defd02fda-linux_amd64.tar.gz"
hash = "a5b4ce5d16f218e78217557da510face883d30e65bcf1c6aa4d29486f12b14d7"

[pkg.forc-node.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-node-0.71.3%2Bnightly.20260803.9defd02fda-linux_arm64.tar.gz"
hash = "4df83801d86b55b74a57702af8823d87c8091636fd45d882394d210e4b90d318"

[pkg.forc-wallet]
version = "0.16.4+nightly.20260803.9defd02fda"

[pkg.forc-wallet.target.darwin_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-wallet-0.16.4%2Bnightly.20260803.9defd02fda-darwin_amd64.tar.gz"
hash = "f52c4dfb54463e0c01a924a71c76c965d5def43e03a55596922027ed8d14e398"

[pkg.forc-wallet.target.darwin_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-wallet-0.16.4%2Bnightly.20260803.9defd02fda-darwin_arm64.tar.gz"
hash = "e009ee1c3f8ec4054d03a5b94bab87f6f2680f46d6d3d43095868f9998af9516"

[pkg.forc-wallet.target.linux_amd64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-wallet-0.16.4%2Bnightly.20260803.9defd02fda-linux_amd64.tar.gz"
hash = "20f66e5ee0c22ed9901c24de810080a0e225d811153d93b860db6811da0e9a36"

[pkg.forc-wallet.target.linux_arm64]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/forc-wallet-0.16.4%2Bnightly.20260803.9defd02fda-linux_arm64.tar.gz"
hash = "e7222325340f88fea6be144c9587044353dec408d353b62cd2d3bf65a14f1f44"

[pkg.fuel-core]
version = "0.48.2+nightly.20260803.540fb5f1af"

[pkg.fuel-core.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-aarch64-apple-darwin.tar.gz"
hash = "11799d91c52f532b8c944e0676fd579bbb9faeaf5bcdb4da46338684da3ff0a1"

[pkg.fuel-core.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-aarch64-unknown-linux-gnu.tar.gz"
hash = "bbbab804619e0bea44fe1004fe41c9c3399cabc939a60d24dfd44d35fa10d0f4"

[pkg.fuel-core.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-x86_64-apple-darwin.tar.gz"
hash = "0760161c82d8ccb0334094fd674733dcdabb1b068199f12c841ec1db56366036"

[pkg.fuel-core.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-x86_64-unknown-linux-gnu.tar.gz"
hash = "ded0be3c9c54bc9072cbc021b6f6bf80ec36b36df1feabcb2f1568fa2242a5fb"

[pkg.fuel-core-keygen]
version = "0.48.2+nightly.20260803.540fb5f1af"

[pkg.fuel-core-keygen.target.aarch64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-aarch64-apple-darwin.tar.gz"
hash = "11799d91c52f532b8c944e0676fd579bbb9faeaf5bcdb4da46338684da3ff0a1"

[pkg.fuel-core-keygen.target.aarch64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-aarch64-unknown-linux-gnu.tar.gz"
hash = "bbbab804619e0bea44fe1004fe41c9c3399cabc939a60d24dfd44d35fa10d0f4"

[pkg.fuel-core-keygen.target.x86_64-apple-darwin]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-x86_64-apple-darwin.tar.gz"
hash = "0760161c82d8ccb0334094fd674733dcdabb1b068199f12c841ec1db56366036"

[pkg.fuel-core-keygen.target.x86_64-unknown-linux-gnu]
url = "https://github.com/FuelLabs/sway-nightly-binaries/releases/download/nightly-20260803/fuel-core-0.48.2%2Bnightly.20260803.540fb5f1af-x86_64-unknown-linux-gnu.tar.gz"
hash = "ded0be3c9c54bc9072cbc021b6f6bf80ec36b36df1feabcb2f1568fa2242a5fb"
